config/routes.rb
Rails.application.routes.draw do
  get 'game', to: "pages#game"
  post 'score', to: "pages#score"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/pages_controller.rb
require 'open-uri'
require 'json'

class PagesController < ApplicationController

  ALPHABET = ("A".."Z").to_a
  VOWELS = ["A", "E", "I", "O", "U"]

  def game
    @time_start = Time.now
    @letters = generate_grid(10)
  end

  def score
    @time_submit = Time.now
    @input = params[:word]
    @letters = params["letters"]
    @time_start = Time.parse(params["start_time"])
    @message = run_game(@input, @letters, @time_start, @time_submit)
  end

  def generate_grid(grid_size)
    # TODO: generate random grid of letters
    grid = []
    grid = (0...grid_size).map do
      ALPHABET[rand(ALPHABET.size )]
    end
    grid << VOWELS[rand(VOWELS.length)]
    grid
  end

  def in_grid?(attempt, grid)
    puts "got in: attempt"
    p grid
    attempt_arr = attempt.upcase.split("")

    attempt_arr.each do |letter|
      return false if attempt_arr.count(letter) > grid.count(letter)
      # true
    end
  end

  def valid_word?(attempt)
    url = "https://wagon-dictionary.herokuapp.com/#{attempt}"
    validation_serialized = open(url).read
    is_valid = JSON.parse(validation_serialized)
    is_valid["found"]
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: 0, score: 0, message: "" }

    if !in_grid?(attempt, grid)
      result[:message] = "Your word is not in the grid"
    elsif !valid_word?(attempt)
      result[:message] = "That is not an english word"
    else
      result[:message] = "Well done"
      result[:score] = (5 + (100 - (end_time - start_time)) + attempt.length).to_i
      result[:time] = end_time - start_time
    end

    result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/game.html.erb
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/application.css">
  </head>
  <body>
    <div class="wrapper">
      <h1>Here is your grid!</h1>
      <ul class="grid">
        <% @letters.each do |letter| %>
          <li><%= letter %></li>
        <%end%>
      </ul>

      <form action="/score" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="text" name="word">
        <input type="submit" value="Sumbit your word">
        <%= hidden_field_tag "letters", @letters %>
        <%= hidden_field_tag "start_time", @time_start %>

      </form>
    </div>

  </body>
</html>

app/views/pages/score.html.erb
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/application.css">
  </head>
  <body>
    <div class="wrapper">
      <h1><%= @message[:message] %></h1>
      <h2>You took <strong><%= @message[:time] %></strong> seconds to reply the word <strong><%= @input %></strong>, for a total of <strong><%= @message[:score] %></strong> points!</h2>
    </div>

    <%= link_to "Play again", game_path %>

  </body>
</html>